### ISSUE TITLE
Discussion on closing AMQP link when no partitions are available

### ISSUE THREAD

**Issue by ppatierno** [ppatierno/amqp-kafka-bridge#10]
Currently, if an AMQP receiver link is attached but no partitions are available on the topic because they are already assigned to other receivers, the attach link request is refused (detached).
Is it correct ? Or the link could remain attached, the receiver won't receive any message of course but when other receivers will disconnect, the Kafka coordinator'll reassign partitions and the new receiver will start to receive messages,

**Comment by grs** [comment]
I thought you could have multiple non-competing consumers on a given partition of a topic, no? I.e. each of the receivers sees all messages and they separately track their position in it?

**Comment by ppatierno** [comment]
It's true when consumers are in different consumer groups (identified by a group.id).
i.e.
We have a topic with 4 partitions
If I have 5 consumers and each of them requests to be part of a different consumer group (i.e. group1, group2, ... group5) they'll receive all messages published on the topic (spreaded on all 4 partitions).
If all 5 consumers ask to be part of same consumer group (i.e. group1) then the first 4 will get a partition and will receive messages from them (one consumer per one partition) ... the 5th will be out ! No partition available for it.
A partition can have only one consumer for each consumer group, this is the reason.

**Comment by grs** [comment]
Makes sense thanks! Back to the original question, I think both options are reasonable, so I'd start with which ever is easier if there is a difference. If not, I'd probably allow the link to remain attached but just not get any messages until a partition was freed up for that consumer group.

**Comment by ppatierno** [comment]
Current implementation kick-off the receiver if no partitions are available and the link is detached.
Could we think to do that configurable ? Does it make sense for you ?

**Comment by grs** [comment]
On 30/03/16 16:38, Paolo Patierno wrote:
> Current implementation kick-off the receiver if no partitions are
> available and the link is detached.

I think that is fine also.

> Could we think to do that configurable ?

Maybe in the future, but for now I would just go with what you have already.

**Comment by ppatierno** [comment]
As discussed the current solution (link is detached) is applied.
